services:
  postgres:
    image: postgres:16
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
  integresql:
    image: allaboutapps/integresql
    profiles:
      - testing
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      INTEGRESQL_PGPASSWORD: $POSTGRES_PASSWORD
      INTEGRESQL_PGUSER: $POSTGRES_USER
      INTEGRESQL_PGDATABASE: $POSTGRES_DB
      INTEGRESQL_PGHOST: postgres
    ports:
      - '5000:5000'

volumes:
  postgres-data:
