import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateProductsTable implements MigrationInterface {
  name = 'CreateProductsTable1719220180803';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(/* sql */ `CREATE TABLE "products" (
      "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      "name" character varying NOT NULL,
      "model_year" integer NOT NULL,
      "list_price" numeric(8,2) NOT NULL,
      "brand_id" bigint NOT NULL,
      "category_id" bigint NOT NULL,
      CONSTRAINT "CHK_847c8949f0bb5a090d99a3b367" CHECK ("model_year" >= 1970),
      CONSTRAINT "CHK_79c0e3caad1d7404cbea7b9704" CHECK ("list_price" > 0),
      CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id")
    )`);
    await queryRunner.query(/* sql */ `ALTER TABLE "products"
      ADD CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df"
        FOREIGN KEY ("brand_id")
        REFERENCES "brands"("id")
          ON DELETE CASCADE
          ON UPDATE CASCADE`);
    await queryRunner.query(/* sql */ `ALTER TABLE "products"
      ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"
        FOREIGN KEY ("category_id")
        REFERENCES "categories"("id")
          ON DELETE CASCADE
          ON UPDATE CASCADE`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(/* sql */ `ALTER TABLE "products"
      DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
    await queryRunner.query(/* sql */ `ALTER TABLE "products"
      DROP CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df"`);
    await queryRunner.query(/* sql */ `DROP TABLE "products"`);
  }
}
