import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateCustomersTable implements MigrationInterface {
  name = 'CreateCustomersTable1719509356809';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(/*sql*/ `CREATE TABLE "customers" (
      "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      "first_name" character varying NOT NULL,
      "last_name" character varying NOT NULL,
      "email" character varying NOT NULL,
      "phone" character varying,
      "street" character varying,
      "city" character varying,
      "state" character varying,
      "zip_code" character varying,
      CONSTRAINT "UQ_8536b8b85c06969f84f0c098b03" UNIQUE ("email"),
      CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id")
    )`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(/*sql*/ `DROP TABLE "customers"`);
  }
}
