import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateCategoriesTable implements MigrationInterface {
  name = 'CreateCategoriesTable1719002522747';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(/* sql */ `CREATE TABLE "categories" (
      "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      "name" character varying NOT NULL,
      CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id")
    )`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(/* sql */ `DROP TABLE "categories"`);
  }
}
