import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateStoresTable implements MigrationInterface {
  name = 'CreateStoresTable1720142160331';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(/* sql */ `CREATE TABLE "stores" (
      "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
      "name" character varying NOT NULL,
      "phone" character varying,
      "email" character varying,
      "street" character varying,
      "city" character varying,
      "state" character varying,
      "zip_code" character varying,
      CONSTRAINT "PK_f3172007d4de5ae8e7692759d79" PRIMARY KEY ("id")
    )`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(/* sql */ `DROP TABLE "store"`);
  }
}
